default:
  image: fabernovel/android:api-34-v1.8.0
  tags:
    - loki

stages:
  - ci
  - cd
  - deploy_pages

workflow:
  auto_cancel:
    on_new_commit: conservative
    on_job_failure: all

ci:
  stage: ci
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
  script:
    - ./gradlew detekt
    - ./gradlew lintKotlin
    - ./gradlew lint
    - mkdir app/keystore
    - touch app/keystore/release.jks
    - echo "${DAEDALUS_KEYSTORE}" | base64 -d > app/keystore/release.jks
    - ./gradlew assemble
    - ./gradlew test

cd:
  stage: cd
  needs:
    - job: ci
      artifacts: true
  rules:
    - when: manual
  script:
    - echo "foo"
  release:
    name: "Foo"
    description: "Bar"
    tag_name: "foo"
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: "asset1"
          url: "https://example.com/assets/1"
          filepath: "app/build/outputs/apk/release/app-release.apk"

deploy_pages:
  image: ruby:3.4
  stage: deploy_pages
  when: manual
  pages: true
  script:
    - gem install bundler
    - bundle install
    - bundle exec jekyll build -s website -d public
  artifacts:
    paths:
      - public
