default:
  image: fabernovel/android:api-34-v1.8.0
  tags:
    - loki

stages:
  - ci
  - deploy_pages

workflow:
  auto_cancel:
    on_new_commit: conservative
    on_job_failure: all

ci:
  stage: ci
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - ./gradlew detekt
    - ./gradlew lintKotlin
    - ./gradlew lint
    - mkdir app/keystore
    - touch app/keystore/release.jks
    - echo "${DAEDALUS_KEYSTORE}" | base64 -d > app/keystore/release.jks
    - ./gradlew assemble
    - ./gradlew test

deploy_pages:
  image: ruby:3.2
  stage: deploy_pages
  pages: true
  script:
    - gem install bundler
    - bundle install
    - bundle exec jekyll build -s website -d public
  artifacts:
    paths:
      - public
