name: CD
on:
  workflow_dispatch:
jobs:
  cd:
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: oracle

      - name: Setup Android SDK
        uses: amyu/setup-android@v4
        with:
          cache-disabled: true

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Decode keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: "release.jks"
          fileDir: "${{ github.workspace }}/app/keystore"
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Build release
        run: ./gradlew app:assembleRelease
        env:
          DAEDALUS_SIGNING_KEY: ${{ secrets.DAEDALUS_SIGNING_KEY }}
          DAEDALUS_STORE_PASSWORD: ${{ secrets.DAEDALUS_STORE_PASSWORD }}
          DAEDALUS_SIGNING_KEY_PASSWORD: ${{ secrets.DAEDALUS_SIGNING_KEY_PASSWORD }}

      - name: Get current version
        run: echo "version=$(./gradlew version -q)" >> $GITHUB_OUTPUT
        id: version

      - name: Get current version code
        run: echo "versionCode=$(./gradlew versionCode -q)" >> $GITHUB_OUTPUT
        id: versionCode

      - name: Get current date
        run: echo "builddate=$(date +"%Y-%m-%dT%H-%M-%S")" >> $GITHUB_OUTPUT
        id: date

      - name: Create release tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          tag_prefix: ""
          github_token: ${{ github.token }}
          custom_tag: Release/V${{ steps.version.outputs.version }}_${{ steps.date.outputs.builddate }}

      - name: Upload APK to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: "${{ github.workspace }}/app/build/outputs/apk/release/app-release.apk"
          release_name: "Daedalus ${{ steps.version.outputs.version }} (${{ steps.versionCode.outputs.versionCode }})"
          asset_name: "Daedalus-${{ steps.version.outputs.version }}-${{ steps.versionCode.outputs.versionCode }}"
          tag: Release/V${{ steps.version.outputs.version }}_${{ steps.date.outputs.builddate }}
